IMPORTAR LIBRERÍAS

In [1]:
import pandas as pd
import numpy as np

VER EL DATASET

In [2]:
#importar archivo csv en un DataFrame
#parse_dates para interpretar la columna de "date" como fechas 
ruta_archivo = r"C:/Users/mguer/Desktop/data_latinoamerica.csv"

df_covid = pd.read_csv(ruta_archivo, parse_dates=["date"])

df_covid

,location_key,date,country_code,country_name,new_confirmed,new_deceased,cumulative_confirmed,cumulative_deceased,cumulative_vaccine_doses_administered,population,...,population_largest_city,area_rural_sq_km,area_urban_sq_km,life_expectancy,adult_male_mortality_rate,adult_female_mortality_rate,pollution_mortality_rate,comorbidity_mortality_rate,new_recovered,cumulative_recovered
0,AR,2020-01-01,AR,Argentina,3.0,0.0,3.0,0.0,NaN,44938712.0,...,15057273.0,2690269.0,55032.0,76.52,147.086,79.483,26.6,15.8,NaN,NaN
1,AR,2020-01-02,AR,Argentina,14.0,0.0,17.0,0.0,NaN,44938712.0,...,15057273.0,2690269.0,55032.0,76.52,147.086,79.483,26.6,15.8,NaN,NaN
2,AR,2020-01-03,AR,Argentina,3.0,0.0,20.0,0.0,NaN,44938712.0,...,15057273.0,2690269.0,55032.0,76.52,147.086,79.483,26.6,15.8,NaN,NaN
3,AR,2020-01-04,AR,Argentina,7.0,0.0,27.0,0.0,NaN,44938712.0,...,15057273.0,2690269.0,55032.0,76.52,147.086,79.483,26.6,15.8,NaN,NaN
4,AR,2020-01-05,AR,Argentina,5.0,0.0,32.0,0.0,NaN,44938712.0,...,15057273.0,2690269.0,55032.0,76.52,147.086,79.483,26.6,15.8,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12216052,VE_Z,2022-09-13,VE,Venezuela,NaN,NaN,NaN,NaN,NaN,1422000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12216053,VE_Z,2022-09-14,VE,Venezuela,NaN,NaN,NaN,NaN,NaN,1422000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12216054,VE_Z,2022-09-15,VE,Venezuela,NaN,NaN,NaN,NaN,NaN,1422000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12216055,VE_Z,2022-09-16,VE,Venezuela,NaN,NaN,NaN,NaN,NaN,1422000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12216056,VE_Z,2022-09-17,VE,Venezuela,NaN,NaN,NaN,NaN,NaN,1422000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

1. OBTENER INFORMACIÓN DEL DATASET

In [ ]:
#1.1 Ver el nombre de las columnas
print(df_covid.columns)

Index(['location_key', 'date', 'country_code', 'country_name', 'new_confirmed',
       'new_deceased', 'cumulative_confirmed', 'cumulative_deceased',
       'cumulative_vaccine_doses_administered', 'population',
       'population_male', 'population_female', 'population_rural',
       'population_urban', 'population_density', 'human_development_index',
       'population_age_00_09', 'population_age_10_19', 'population_age_20_29',
       'population_age_30_39', 'population_age_40_49', 'population_age_50_59',
       'population_age_60_69', 'population_age_70_79',
       'population_age_80_and_older', 'gdp_usd', 'gdp_per_capita_usd',
       'latitude', 'longitude', 'area_sq_km', 'smoking_prevalence',
       'diabetes_prevalence', 'infant_mortality_rate', 'nurses_per_1000',
       'physicians_per_1000', 'average_temperature_celsius',
       'minimum_temperature_celsius', 'maximum_temperature_celsius',
       'rainfall_mm', 'relative_humidity', 'population_largest_city',
       'area_rural_sq_km', 'area_urban_sq_km', 'life_expectancy',
       'adult_male_mortality_rate', 'adult_female_mortality_rate',
       'pollution_mortality_rate', 'comorbidity_mortality_rate',
       'new_recovered', 'cumulative_recovered'],
      dtype='object')

2. LIMPIEZA Y FILTRADO DE DATOS --> se crea nuevo dataset: "df_limpio"

#2.2 FILTRADO DE PAÍSES:
Se observan 3 columnas con información acerca de los países:
- country_code
- country_name
- location_key

Se solicitan la cantidad y descripción de los valores únicos de dichas 3 columnas para elegir sobre cuál realizar el filtrado de datos.

In [ ]:
# valores únicos de la columna country_code
valores_unicos = df_covid['country_code'].unique()

print("Valores únicos de la columna country_code ", valores_unicos)
print("Cantidad de valores únicos de la columna country_code ", len(df_covid['country_code'].unique()))

# valores únicos de la columna country_name
valores_unicos = df_covid['country_name'].unique()

print("Valores únicos de la columna country_name ", valores_unicos)
print("Cantidad de valores únicos de la columna country_name ", len(df_covid['country_name'].unique()))

# valores únicos de la columna location_key
valores_unicos = df_covid['location_key'].unique()

print("Valores únicos de la columna location_key ", valores_unicos)
print("Cantidad de valores únicos de la columna location_key ", len(df_covid['location_key'].unique()))

Valores únicos de la columna country_code  ['AR' 'BO' 'BR' 'CL' 'CO' 'CR' 'CU' 'DO' 'EC' 'GT' 'HN' 'MX' 'NI' 'PA'
 'PE' 'PR' 'PY' 'SV' 'UY' 'VE']
Cantidad de valores únicos de la columna country_code  20
Valores únicos de la columna country_name  ['Argentina' 'Bolivia' 'Brazil' 'Chile' 'Colombia' 'Costa Rica' 'Cuba'
 'Dominican Republic' 'Ecuador' 'Guatemala' 'Honduras' 'Mexico'
 'Nicaragua' 'Panama' 'Peru' 'Puerto Rico' 'Paraguay' 'El Salvador'
 'Uruguay' 'Venezuela']
Cantidad de valores únicos de la columna country_name  20
Valores únicos de la columna location_key  ['AR' 'AR_A' 'AR_A_007' ... 'VE_X' 'VE_Y' 'VE_Z']
Cantidad de valores únicos de la columna location_key  12327

In [19]:
# Lista de países donde se expandirá Biogenesys según country_name
paises_biogenesys = ["Argentina", "Brazil", "Chile", "Colombia", "Mexico", "Peru"]

# Mantener solo las filas donde 'country_name' esté en la lista
df_limpio = df_limpio[df_limpio["country_name"].isin(paises_biogenesys)]

print("Países filtrados: Ahora el data set df_limpio contiene solo:")
print(df_limpio["country_name"].unique())

# Mostrar el total de filas y columnas
print(f"Dimensiones del dataset: {df_limpio.shape}")

Países filtrados: Ahora el data set df_limpio contiene solo:
['Argentina' 'Brazil' 'Chile' 'Colombia' 'Mexico' 'Peru']
Dimensiones del dataset: (11445522, 29)

In [20]:
#2.3 Filtrado de datos a partir de la fecha 2021-01-01

# Convertir la columna 'date' a formato de fecha
df_limpio["date"] = pd.to_datetime(df_limpio["date"])

# Filtrado de fechas
df_limpio = df_limpio[df_limpio["date"] >= "2021-01-01"]

# Verificar los resultados
print("Filtro de fecha aplicado.")
print(f"Nuevas dimensiones del dataset: {df_limpio.shape}")
print(f"La fecha más antigua ahora es: {df_limpio['date'].min()}")

Filtro de fecha aplicado.
Nuevas dimensiones del dataset: (7225527, 29)
La fecha más antigua ahora es: 2021-01-01 00:00:00

In [21]:
# 1. Calculamos la cantidad de nulos por columna
nulos_cantidad = df_limpio.isnull().sum()

# 2. Calculamos el porcentaje (para entender la gravedad)
nulos_porcentaje = (df_limpio.isnull().mean() * 100).round(2)

# 3. Creamos un DataFrame para verlo bonito
df_nulos = pd.DataFrame({
    "Cantidad Nulos": nulos_cantidad,
    "Porcentaje (%)": nulos_porcentaje
})

# 4. Filtramos para ver SOLO las columnas que tienen algún nulo (ordenadas de mayor a menor)
df_nulos_filtrado = df_nulos[df_nulos["Cantidad Nulos"] > 0].sort_values("Porcentaje (%)", ascending=False)

print("--- REPORTE DE VALORES FALTANTES ---")
display(df_nulos_filtrado)

--- REPORTE DE VALORES FALTANTES ---

                             Cantidad Nulos  Porcentaje (%)
human_development_index             3758027           52.01
cumulative_deceased                 2844753           39.37
new_deceased                        2844753           39.37
new_confirmed                       2842083           39.33
cumulative_confirmed                2842083           39.33
area_sq_km                          1013597           14.03
population_age_00_09                 600527            8.31
population_age_10_19                 600527            8.31
population_age_30_39                 600527            8.31
population_age_80_and_older          600527            8.31
population_age_60_69                 600527            8.31
population_age_70_79                 600527            8.31
population_age_20_29                 600527            8.31
population_age_50_59                 600527            8.31
population_age_40_49                 600527            8.31
population_female                    386770            5.35
population_male                      386770            5.35
rainfall_mm                          374440            5.18
relative_humidity                    340867            4.72
maximum_temperature_celsius          340455            4.71
average_temperature_celsius          340422            4.71
minimum_temperature_celsius          340472            4.71
latitude                             258750            3.58
longitude                            258750            3.58
population                            73288            1.01

In [27]:
df_limpio.info()
df_limpio

<class 'pandas.core.frame.DataFrame'>
Index: 7225527 entries, 366 to 12136776
Data columns (total 29 columns):
 #   Column                       Dtype
---  ------                       -----
 0   location_key                 object
 1   date                         datetime64[ns]
 2   country_code                 object
 3   country_name                 object
 4   new_confirmed                float64
 5   new_deceased                 float64
 6   cumulative_confirmed         float64
 7   cumulative_deceased          float64
 8   population                   float64
 9   population_male              float64
 10  population_female            float64
 11  human_development_index      float64
 12  population_age_00_09         float64
 13  population_age_10_19         float64
 14  population_age_20_29         float64
 15  population_age_30_39         float64
 16  population_age_40_49         float64
 17  population_age_50_59         float64
 18  population_age_60_69         float64
 19  population_age_70_79         float64
 20  population_age_80_and_older  float64
 21  latitude                     float64
 22  longitude                    float64
 23  area_sq_km                   float64
 24  average_temperature_celsius  float64
 25  minimum_temperature_celsius  float64
 26  maximum_temperature_celsius  float64
 27  rainfall_mm                  float64
 28  relative_humidity            float64
dtypes: datetime64[ns](1), float64(25), object(3)
memory usage: 1.6+ GB

,location_key,date,country_code,country_name,new_confirmed,new_deceased,cumulative_confirmed,cumulative_deceased,population,population_male,...,population_age_70_79,population_age_80_and_older,latitude,longitude,area_sq_km,average_temperature_celsius,minimum_temperature_celsius,maximum_temperature_celsius,rainfall_mm,relative_humidity
366,AR,2021-01-01,AR,Argentina,2685.0,140.0,1662867.0,46522.0,44938712.0,19523766.0,...,1817557.0,994030.0,-34.000000,-64.000000,2780400.0,26.388889,15.580247,33.030864,0.00000,41.559285
367,AR,2021-01-02,AR,Argentina,7767.0,166.0,1670634.0,46688.0,44938712.0,19523766.0,...,1817557.0,994030.0,-34.000000,-64.000000,2780400.0,27.740741,18.098765,33.962963,0.00000,43.581350
368,AR,2021-01-03,AR,Argentina,4934.0,157.0,1675568.0,46845.0,44938712.0,19523766.0,...,1817557.0,994030.0,-34.000000,-64.000000,2780400.0,21.956790,17.950617,33.456790,13.14450,74.880846
369,AR,2021-01-04,AR,Argentina,13953.0,157.0,1689521.0,47002.0,44938712.0,19523766.0,...,1817557.0,994030.0,-34.000000,-64.000000,2780400.0,24.894444,18.072222,30.244444,1.49860,60.805923
370,AR,2021-01-05,AR,Argentina,14085.0,160.0,1703606.0,47162.0,44938712.0,19523766.0,...,1817557.0,994030.0,-34.000000,-64.000000,2780400.0,20.104938,16.135802,30.685185,8.28675,72.972595
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12136772,PE_UCA_0401,2022-09-13,PE,Peru,NaN,NaN,NaN,NaN,2860.0,1477.0,...,46.0,9.0,-9.798611,-70.753333,17847.0,31.777778,21.722222,36.722222,16.25600,62.040723
12136773,PE_UCA_0401,2022-09-14,PE,Peru,NaN,NaN,NaN,NaN,2860.0,1477.0,...,46.0,9.0,-9.798611,-70.753333,17847.0,NaN,NaN,NaN,NaN,NaN
12136774,PE_UCA_0401,2022-09-15,PE,Peru,NaN,NaN,NaN,NaN,2860.0,1477.0,...,46.0,9.0,-9.798611,-70.753333,17847.0,NaN,NaN,NaN,NaN,NaN
12136775,PE_UCA_0401,2022-09-16,PE,Peru,NaN,NaN,NaN,NaN,2860.0,1477.0,...,46.0,9.0,-9.798611,-70.753333,17847.0,NaN,NaN,NaN,NaN,NaN
12136776,PE_UCA_0401,2022-09-17,PE,Peru,NaN,NaN,NaN,NaN,2860.0,1477.0,...,46.0,9.0,-9.798611,-70.753333,17847.0,NaN,NaN,NaN,NaN,NaN

In [ ]:
import pandas as pd

# Ruta del archivo original
ruta_archivo = r"C:/Users/mguer/Desktop/data_latinoamerica.csv"

# Lista de países a incluir
paises_expansion = ['Argentina', 'Brasil', 'Chile', 'Colombia', 'Mexico', 'Peru']

# Nombre del archivo filtrado de salida
salida = "C:/Users/mguer/Desktop/DatosFinalesFiltrado.csv"

# Leer por partes
chunks = pd.read_csv(
    ruta_archivo,
    parse_dates=["date"],
    chunksize=1000000
)

# Filtrar y guardar por partes
for i, chunk in enumerate(chunks):
    df_filtrado = chunk[
        (chunk['country_name'].isin(paises_expansion)) &
        (chunk['date'] > '2021-01-01')
    ]

    # Guardar en el CSV final (agrega en modo 'append')
    df_filtrado.to_csv(salida, mode='a', index=False, header=(i == 0))

    print(f"Chunk {i+1} procesado: {len(df_filtrado)} filas guardadas.")

print("✅ Proceso finalizado. Archivo filtrado guardado en:")
print(salida)

Chunk 1 procesado: 340080 filas guardadas.
Chunk 2 procesado: 0 filas guardadas.
Chunk 3 procesado: 0 filas guardadas.
Chunk 4 procesado: 0 filas guardadas.
Chunk 5 procesado: 0 filas guardadas.
Chunk 6 procesado: 0 filas guardadas.
Chunk 7 procesado: 556808 filas guardadas.
Chunk 8 procesado: 551073 filas guardadas.
Chunk 9 procesado: 629697 filas guardadas.
Chunk 10 procesado: 629697 filas guardadas.
Chunk 11 procesado: 609729 filas guardadas.
Chunk 12 procesado: 629697 filas guardadas.
Chunk 13 procesado: 86131 filas guardadas.
✅ Proceso finalizado. Archivo filtrado guardado en:
C:/Users/mguer/Desktop/DatosFinalesFiltrado.csv

In [4]:
#importar archivo csv en un DataFrame
#parse_dates para interpretar la columna de "date" como fechas 
ruta_archivo_filtrado = r"C:\Users\mguer\Desktop\DatosFinalesFiltrado.csv"

df_covid_filtrado = pd.read_csv(ruta_archivo_filtrado, parse_dates=["date"])

df_covid_filtrado.shape

C:\Users\mguer\AppData\Local\Temp\ipykernel_34412\1821612923.py:5: DtypeWarning: Columns (4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49) have mixed types. Specify dtype option on import or set low_memory=False.
  df_covid_filtrado = pd.read_csv(ruta_archivo_filtrado, parse_dates=["date"])

(4929801, 50)

In [5]:
df_covid_filtrado

,location_key,date,country_code,country_name,new_confirmed,new_deceased,cumulative_confirmed,cumulative_deceased,cumulative_vaccine_doses_administered,population,...,population_largest_city,area_rural_sq_km,area_urban_sq_km,life_expectancy,adult_male_mortality_rate,adult_female_mortality_rate,pollution_mortality_rate,comorbidity_mortality_rate,new_recovered,cumulative_recovered
0,AR,2021-01-02,AR,Argentina,7767.0,166.0,1670634.0,46688.0,20334.0,44938712.0,...,15057273.0,2690269.0,55032.0,76.52,147.086,79.483,26.6,15.8,NaN,NaN
1,AR,2021-01-03,AR,Argentina,4934.0,157.0,1675568.0,46845.0,20529.0,44938712.0,...,15057273.0,2690269.0,55032.0,76.52,147.086,79.483,26.6,15.8,NaN,NaN
2,AR,2021-01-04,AR,Argentina,13953.0,157.0,1689521.0,47002.0,25164.0,44938712.0,...,15057273.0,2690269.0,55032.0,76.52,147.086,79.483,26.6,15.8,NaN,NaN
3,AR,2021-01-05,AR,Argentina,14085.0,160.0,1703606.0,47162.0,29852.0,44938712.0,...,15057273.0,2690269.0,55032.0,76.52,147.086,79.483,26.6,15.8,NaN,NaN
4,AR,2021-01-06,AR,Argentina,14496.0,131.0,1718102.0,47293.0,34162.0,44938712.0,...,15057273.0,2690269.0,55032.0,76.52,147.086,79.483,26.6,15.8,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4929796,PE_UCA_0401,2022-09-13,PE,Peru,NaN,NaN,NaN,NaN,NaN,2860.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4929797,PE_UCA_0401,2022-09-14,PE,Peru,NaN,NaN,NaN,NaN,NaN,2860.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4929798,PE_UCA_0401,2022-09-15,PE,Peru,NaN,NaN,NaN,NaN,NaN,2860.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4929799,PE_UCA_0401,2022-09-16,PE,Peru,NaN,NaN,NaN,NaN,NaN,2860.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4929800,PE_UCA_0401,2022-09-17,PE,Peru,NaN,NaN,NaN,NaN,NaN,2860.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df = pd.read_csv(r"C:\Users\mguer\Desktop\DatosFinalesFiltrado.csv", nrows=2500000)
df.to_csv(r"C:\Users\mguer\Desktop\DatosFinalesFiltradoMuestra.csv", index=False)

In [5]:
# valores únicos de la columna location_key
valores_unicos = df_covid['location_key'].unique()

print("Valores únicos de la columna location_key ", valores_unicos)
print("Cantidad de valores únicos de la columna location_key ", len(df_covid['location_key'].unique()))

Valores únicos de la columna location_key  ['AR' 'AR_A' 'AR_A_007' ... 'VE_X' 'VE_Y' 'VE_Z']
Cantidad de valores únicos de la columna location_key  12327

In [7]:
# 1. Filtramos solo las filas de Argentina
filtro_arg = df_covid['country_name'] == 'Argentina'

# 2. Obtenemos los valores únicos de 'location_key' en esas filas
valores_unicos_arg = df_covid.loc[filtro_arg, 'location_key'].unique()

# 3. Mostramos los resultados
print(f"Cantidad de códigos distintos (location_key) en Argentina: {len(valores_unicos_arg)}")
print("\n--- LISTA DE VALORES ÚNICOS ARG---")
print(valores_unicos_arg)

# Lo mismo para los demás países
filtro_bra = df_covid['country_name'] == 'Brazil'
valores_unicos_bra = df_covid.loc[filtro_bra, 'location_key'].unique()
print(f"Cantidad de códigos distintos (location_key) en Brazil: {len(valores_unicos_bra)}")
print("\n--- LISTA DE VALORES ÚNICOS BRA---")
print(valores_unicos_bra)

filtro_col = df_covid['country_name'] == 'Colombia'
valores_unicos_col = df_covid.loc[filtro_col, 'location_key'].unique()
print(f"Cantidad de códigos distintos (location_key) en Colombia: {len(valores_unicos_col)}")
print("\n--- LISTA DE VALORES ÚNICOS COL---")
print(valores_unicos_col)

filtro_chi = df_covid['country_name'] == 'Chile'
valores_unicos_chi = df_covid.loc[filtro_chi, 'location_key'].unique()
print(f"Cantidad de códigos distintos (location_key) en Chile: {len(valores_unicos_chi)}")
print("\n--- LISTA DE VALORES ÚNICOS CHI---")
print(valores_unicos_chi)

filtro_mex = df_covid['country_name'] == 'Mexico'
valores_unicos_mex = df_covid.loc[filtro_mex, 'location_key'].unique()
print(f"Cantidad de códigos distintos (location_key) en Mexico: {len(valores_unicos_mex)}")
print("\n--- LISTA DE VALORES ÚNICOS MEX---")
print(valores_unicos_mex)

filtro_per = df_covid['country_name'] == 'Peru'
valores_unicos_per = df_covid.loc[filtro_per, 'location_key'].unique()
print(f"Cantidad de códigos distintos (location_key) en Peru: {len(valores_unicos_per)}")
print("\n--- LISTA DE VALORES ÚNICOS PER---")
print(valores_unicos_per)

Cantidad de códigos distintos (location_key) en Argentina: 545

--- LISTA DE VALORES ÚNICOS ARG---
['AR' 'AR_A' 'AR_A_007' 'AR_A_014' 'AR_A_021' 'AR_A_028' 'AR_A_035'
 'AR_A_042' 'AR_A_049' 'AR_A_056' 'AR_A_070' 'AR_A_077' 'AR_A_098'
 'AR_A_105' 'AR_A_112' 'AR_A_119' 'AR_A_126' 'AR_A_133' 'AR_A_140'
 'AR_A_147' 'AR_A_154' 'AR_A_161' 'AR_B' 'AR_B_007' 'AR_B_014' 'AR_B_021'
 'AR_B_028' 'AR_B_035' 'AR_B_042' 'AR_B_049' 'AR_B_056' 'AR_B_063'
 'AR_B_070' 'AR_B_077' 'AR_B_084' 'AR_B_091' 'AR_B_098' 'AR_B_105'
 'AR_B_112' 'AR_B_119' 'AR_B_126' 'AR_B_134' 'AR_B_140' 'AR_B_147'
 'AR_B_154' 'AR_B_161' 'AR_B_168' 'AR_B_175' 'AR_B_182' 'AR_B_189'
 'AR_B_196' 'AR_B_203' 'AR_B_210' 'AR_B_217' 'AR_B_224' 'AR_B_231'
 'AR_B_238' 'AR_B_245' 'AR_B_252' 'AR_B_260' 'AR_B_266' 'AR_B_270'
 'AR_B_274' 'AR_B_277' 'AR_B_280' 'AR_B_287' 'AR_B_294' 'AR_B_301'
 'AR_B_308' 'AR_B_315' 'AR_B_322' 'AR_B_329' 'AR_B_336' 'AR_B_343'
 'AR_B_351' 'AR_B_357' 'AR_B_364' 'AR_B_371' 'AR_B_385' 'AR_B_392'
 'AR_B_399' 'AR_B_406' 'AR_B_408' 'AR_B_410' 'AR_B_412' 'AR_B_413'
 'AR_B_420' 'AR_B_427' 'AR_B_434' 'AR_B_441' 'AR_B_448' 'AR_B_455'
 'AR_B_462' 'AR_B_469' 'AR_B_476' 'AR_B_483' 'AR_B_490' 'AR_B_497'
 'AR_B_505' 'AR_B_511' 'AR_B_515' 'AR_B_518' 'AR_B_525' 'AR_B_532'
 'AR_B_539' 'AR_B_547' 'AR_B_553' 'AR_B_560' 'AR_B_568' 'AR_B_574'
 'AR_B_581' 'AR_B_588' 'AR_B_595' 'AR_B_602' 'AR_B_609' 'AR_B_616'
 'AR_B_623' 'AR_B_630' 'AR_B_638' 'AR_B_644' 'AR_B_648' 'AR_B_651'
 'AR_B_655' 'AR_B_658' 'AR_B_665' 'AR_B_672' 'AR_B_679' 'AR_B_686'
 'AR_B_693' 'AR_B_700' 'AR_B_707' 'AR_B_714' 'AR_B_721' 'AR_B_728'
 'AR_B_735' 'AR_B_742' 'AR_B_749' 'AR_B_756' 'AR_B_760' 'AR_B_763'
 'AR_B_770' 'AR_B_778' 'AR_B_784' 'AR_B_791' 'AR_B_798' 'AR_B_805'
 'AR_B_812' 'AR_B_819' 'AR_B_826' 'AR_B_833' 'AR_B_840' 'AR_B_847'
 'AR_B_854' 'AR_B_861' 'AR_B_868' 'AR_B_875' 'AR_B_882' 'AR_C' 'AR_C_001'
 'AR_C_002' 'AR_C_003' 'AR_C_004' 'AR_C_005' 'AR_C_006' 'AR_C_007'
 'AR_C_008' 'AR_C_009' 'AR_C_010' 'AR_C_011' 'AR_C_012' 'AR_C_013'
 'AR_C_014' 'AR_C_015' 'AR_D' 'AR_D_007' 'AR_D_014' 'AR_D_021' 'AR_D_028'
 'AR_D_035' 'AR_D_042' 'AR_D_049' 'AR_D_056' 'AR_D_063' 'AR_E' 'AR_E_008'
 'AR_E_015' 'AR_E_021' 'AR_E_028' 'AR_E_035' 'AR_E_042' 'AR_E_049'
 'AR_E_056' 'AR_E_063' 'AR_E_070' 'AR_E_077' 'AR_E_084' 'AR_E_088'
 'AR_E_091' 'AR_E_098' 'AR_E_105' 'AR_E_113' 'AR_F' 'AR_F_007' 'AR_F_014'
 'AR_F_021' 'AR_F_028' 'AR_F_035' 'AR_F_042' 'AR_F_049' 'AR_F_056'
 'AR_F_063' 'AR_F_070' 'AR_F_077' 'AR_F_084' 'AR_F_091' 'AR_F_098'
 'AR_F_105' 'AR_F_112' 'AR_F_119' 'AR_F_126' 'AR_G' 'AR_G_007' 'AR_G_014'
 'AR_G_021' 'AR_G_028' 'AR_G_035' 'AR_G_042' 'AR_G_049' 'AR_G_056'
 'AR_G_063' 'AR_G_070' 'AR_G_077' 'AR_G_084' 'AR_G_091' 'AR_G_098'
 'AR_G_105' 'AR_G_112' 'AR_G_119' 'AR_G_126' 'AR_G_133' 'AR_G_140'
 'AR_G_147' 'AR_G_154' 'AR_G_161' 'AR_G_168' 'AR_G_175' 'AR_G_182'
 'AR_G_189' 'AR_H' 'AR_H_007' 'AR_H_014' 'AR_H_021' 'AR_H_028' 'AR_H_036'
 'AR_H_039' 'AR_H_043' 'AR_H_049' 'AR_H_056' 'AR_H_063' 'AR_H_070'
 'AR_H_077' 'AR_H_084' 'AR_H_091' 'AR_H_098' 'AR_H_105' 'AR_H_112'
 'AR_H_119' 'AR_H_126' 'AR_H_133' 'AR_H_140' 'AR_H_147' 'AR_H_154'
 'AR_H_161' 'AR_H_168' 'AR_J' 'AR_J_007' 'AR_J_014' 'AR_J_021' 'AR_J_028'
 'AR_J_035' 'AR_J_042' 'AR_J_049' 'AR_J_056' 'AR_J_063' 'AR_J_070'
 'AR_J_077' 'AR_J_084' 'AR_J_091' 'AR_J_098' 'AR_J_105' 'AR_J_112'
 'AR_J_119' 'AR_J_126' 'AR_J_133' 'AR_K' 'AR_K_007' 'AR_K_014' 'AR_K_021'
 'AR_K_028' 'AR_K_035' 'AR_K_042' 'AR_K_049' 'AR_K_056' 'AR_K_063'
 'AR_K_070' 'AR_K_077' 'AR_K_084' 'AR_K_091' 'AR_K_098' 'AR_K_105'
 'AR_K_112' 'AR_L' 'AR_L_007' 'AR_L_014' 'AR_L_021' 'AR_L_028' 'AR_L_035'
 'AR_L_042' 'AR_L_049' 'AR_L_056' 'AR_L_070' 'AR_L_077' 'AR_L_098'
 'AR_L_105' 'AR_L_112' 'AR_L_119' 'AR_L_126' 'AR_L_133' 'AR_L_140'
 'AR_L_147' 'AR_L_154' 'AR_M' 'AR_M_007' 'AR_M_014' 'AR_M_021' 'AR_M_028'
 'AR_M_035' 'AR_M_042' 'AR_M_049' 'AR_M_056' 'AR_M_063' 'AR_M_070'
 'AR_M_077' 'AR_M_084' 'AR_M_091' 'AR_M_098' 'AR_M_105' 'AR_M_112'
 'AR_M_119' 'AR_M_126' 'AR_N' 'AR_N_007' 'AR_N_014' 'AR_N_021' 'AR_N_028'
 'AR_N_035' 'AR_N_042' 'AR_N_049' 'AR_N_056' 'AR_N_063' 'AR_N_070'
 'AR_N_077' 'AR_N_084' 'AR_N_091' 'AR_N_098' 'AR_N_105' 'AR_N_112'
 'AR_N_119' 'AR_P' 'AR_P_007' 'AR_P_014' 'AR_P_021' 'AR_P_028' 'AR_P_035'
 'AR_P_042' 'AR_P_049' 'AR_P_056' 'AR_P_063' 'AR_Q' 'AR_Q_007' 'AR_Q_014'
 'AR_Q_021' 'AR_Q_028' 'AR_Q_035' 'AR_Q_042' 'AR_Q_049' 'AR_Q_056'
 'AR_Q_063' 'AR_Q_070' 'AR_Q_077' 'AR_Q_084' 'AR_Q_091' 'AR_Q_098'
 'AR_Q_105' 'AR_Q_112' 'AR_R' 'AR_R_007' 'AR_R_014' 'AR_R_021' 'AR_R_028'
 'AR_R_035' 'AR_R_042' 'AR_R_049' 'AR_R_063' 'AR_R_070' 'AR_R_077'
 'AR_R_084' 'AR_R_091' 'AR_S' 'AR_S_007' 'AR_S_014' 'AR_S_021' 'AR_S_028'
 'AR_S_035' 'AR_S_042' 'AR_S_049' 'AR_S_056' 'AR_S_063' 'AR_S_070'
 'AR_S_077' 'AR_S_084' 'AR_S_091' 'AR_S_098' 'AR_S_105' 'AR_S_112'
 'AR_S_119' 'AR_S_126' 'AR_S_133' 'AR_T' 'AR_T_007' 'AR_T_014' 'AR_T_021'
 'AR_T_028' 'AR_T_035' 'AR_T_042' 'AR_T_049' 'AR_T_056' 'AR_T_063'
 'AR_T_070' 'AR_T_077' 'AR_T_084' 'AR_T_091' 'AR_T_098' 'AR_T_105'
 'AR_T_112' 'AR_T_119' 'AR_U' 'AR_U_007' 'AR_U_014' 'AR_U_021' 'AR_U_028'
 'AR_U_035' 'AR_U_042' 'AR_U_070' 'AR_U_077' 'AR_U_084' 'AR_U_091'
 'AR_U_098' 'AR_U_105' 'AR_V' 'AR_V_007' 'AR_V_014' 'AR_V_028' 'AR_W'
 'AR_W_007' 'AR_W_014' 'AR_W_021' 'AR_W_028' 'AR_W_035' 'AR_W_042'
 'AR_W_049' 'AR_W_056' 'AR_W_063' 'AR_W_070' 'AR_W_077' 'AR_W_084'
 'AR_W_091' 'AR_W_098' 'AR_W_105' 'AR_W_112' 'AR_W_119' 'AR_W_126'
 'AR_W_133' 'AR_W_140' 'AR_W_147' 'AR_W_154' 'AR_W_161' 'AR_W_168'
 'AR_W_175' 'AR_X' 'AR_X_007' 'AR_X_014' 'AR_X_021' 'AR_X_028' 'AR_X_035'
 'AR_X_042' 'AR_X_049' 'AR_X_056' 'AR_X_063' 'AR_X_070' 'AR_X_077'
 'AR_X_084' 'AR_X_091' 'AR_X_098' 'AR_X_105' 'AR_X_112' 'AR_X_119'
 'AR_X_126' 'AR_X_133' 'AR_X_140' 'AR_X_147' 'AR_X_154' 'AR_X_161'
 'AR_X_168' 'AR_X_175' 'AR_X_182' 'AR_Y' 'AR_Y_007' 'AR_Y_014' 'AR_Y_021'
 'AR_Y_028' 'AR_Y_035' 'AR_Y_042' 'AR_Y_049' 'AR_Y_056' 'AR_Y_063'
 'AR_Y_070' 'AR_Y_077' 'AR_Y_084' 'AR_Y_094' 'AR_Y_098' 'AR_Y_105'
 'AR_Y_112' 'AR_Y_126' 'AR_Y_270' 'AR_Y_308' 'AR_Y_408' 'AR_Z' 'AR_Z_007'
 'AR_Z_014' 'AR_Z_021' 'AR_Z_028' 'AR_Z_035' 'AR_Z_042' 'AR_Z_049']
Cantidad de códigos distintos (location_key) en Brazil: 5616

--- LISTA DE VALORES ÚNICOS BRA---
['BR' 'BR_AC' 'BR_AC_120001' ... 'BR_TO_172130' 'BR_TO_172208'
 'BR_TO_172210']
Cantidad de códigos distintos (location_key) en Colombia: 1156

--- LISTA DE VALORES ÚNICOS COL---
['CO' 'CO_05' 'CO_05_05001' ... 'CO_99_99524' 'CO_99_99624' 'CO_99_99773']
Cantidad de códigos distintos (location_key) en Chile: 363

--- LISTA DE VALORES ÚNICOS CHI---
['CL' 'CL_AI' 'CL_AI_11101' 'CL_AI_11102' 'CL_AI_11201' 'CL_AI_11202'
 'CL_AI_11203' 'CL_AI_11301' 'CL_AI_11302' 'CL_AI_11303' 'CL_AI_11401'
 'CL_AI_11402' 'CL_AN' 'CL_AN_02101' 'CL_AN_02102' 'CL_AN_02103'
 'CL_AN_02104' 'CL_AN_02201' 'CL_AN_02202' 'CL_AN_02203' 'CL_AN_02301'
 'CL_AN_02302' 'CL_AP' 'CL_AP_15101' 'CL_AP_15102' 'CL_AP_15201'
 'CL_AP_15202' 'CL_AR' 'CL_AR_09101' 'CL_AR_09102' 'CL_AR_09103'
 'CL_AR_09104' 'CL_AR_09105' 'CL_AR_09106' 'CL_AR_09107' 'CL_AR_09108'
 'CL_AR_09109' 'CL_AR_09110' 'CL_AR_09111' 'CL_AR_09112' 'CL_AR_09113'
 'CL_AR_09114' 'CL_AR_09115' 'CL_AR_09116' 'CL_AR_09117' 'CL_AR_09118'
 'CL_AR_09119' 'CL_AR_09120' 'CL_AR_09121' 'CL_AR_09201' 'CL_AR_09202'
 'CL_AR_09203' 'CL_AR_09204' 'CL_AR_09205' 'CL_AR_09206' 'CL_AR_09207'
 'CL_AR_09208' 'CL_AR_09209' 'CL_AR_09210' 'CL_AR_09211' 'CL_AT'
 'CL_AT_03101' 'CL_AT_03102' 'CL_AT_03103' 'CL_AT_03201' 'CL_AT_03202'
 'CL_AT_03301' 'CL_AT_03302' 'CL_AT_03303' 'CL_AT_03304' 'CL_BI'
 'CL_BI_08101' 'CL_BI_08102' 'CL_BI_08103' 'CL_BI_08104' 'CL_BI_08105'
 'CL_BI_08106' 'CL_BI_08107' 'CL_BI_08108' 'CL_BI_08109' 'CL_BI_08110'
 'CL_BI_08111' 'CL_BI_08112' 'CL_BI_08201' 'CL_BI_08202' 'CL_BI_08203'
 'CL_BI_08204' 'CL_BI_08205' 'CL_BI_08206' 'CL_BI_08207' 'CL_BI_08301'
 'CL_BI_08302' 'CL_BI_08303' 'CL_BI_08304' 'CL_BI_08305' 'CL_BI_08306'
 'CL_BI_08307' 'CL_BI_08308' 'CL_BI_08309' 'CL_BI_08310' 'CL_BI_08311'
 'CL_BI_08312' 'CL_BI_08313' 'CL_BI_08314' 'CL_CO' 'CL_CO_04101'
 'CL_CO_04102' 'CL_CO_04103' 'CL_CO_04104' 'CL_CO_04105' 'CL_CO_04106'
 'CL_CO_04201' 'CL_CO_04202' 'CL_CO_04203' 'CL_CO_04204' 'CL_CO_04301'
 'CL_CO_04302' 'CL_CO_04303' 'CL_CO_04304' 'CL_CO_04305' 'CL_LI'
 'CL_LI_06101' 'CL_LI_06102' 'CL_LI_06103' 'CL_LI_06104' 'CL_LI_06105'
 'CL_LI_06106' 'CL_LI_06107' 'CL_LI_06108' 'CL_LI_06109' 'CL_LI_06110'
 'CL_LI_06111' 'CL_LI_06112' 'CL_LI_06113' 'CL_LI_06114' 'CL_LI_06115'
 'CL_LI_06116' 'CL_LI_06117' 'CL_LI_06201' 'CL_LI_06202' 'CL_LI_06203'
 'CL_LI_06204' 'CL_LI_06205' 'CL_LI_06206' 'CL_LI_06301' 'CL_LI_06302'
 'CL_LI_06303' 'CL_LI_06304' 'CL_LI_06305' 'CL_LI_06306' 'CL_LI_06307'
 'CL_LI_06308' 'CL_LI_06309' 'CL_LI_06310' 'CL_LL' 'CL_LL_10101'
 'CL_LL_10102' 'CL_LL_10103' 'CL_LL_10104' 'CL_LL_10105' 'CL_LL_10106'
 'CL_LL_10107' 'CL_LL_10108' 'CL_LL_10109' 'CL_LL_10201' 'CL_LL_10202'
 'CL_LL_10203' 'CL_LL_10204' 'CL_LL_10205' 'CL_LL_10206' 'CL_LL_10207'
 'CL_LL_10208' 'CL_LL_10209' 'CL_LL_10210' 'CL_LL_10301' 'CL_LL_10302'
 'CL_LL_10303' 'CL_LL_10304' 'CL_LL_10305' 'CL_LL_10306' 'CL_LL_10307'
 'CL_LL_10401' 'CL_LL_10402' 'CL_LL_10403' 'CL_LL_10404' 'CL_LR'
 'CL_LR_14101' 'CL_LR_14102' 'CL_LR_14103' 'CL_LR_14104' 'CL_LR_14105'
 'CL_LR_14106' 'CL_LR_14107' 'CL_LR_14108' 'CL_LR_14201' 'CL_LR_14202'
 'CL_LR_14203' 'CL_LR_14204' 'CL_MA' 'CL_MA_12101' 'CL_MA_12102'
 'CL_MA_12103' 'CL_MA_12104' 'CL_MA_12201' 'CL_MA_12202' 'CL_MA_12301'
 'CL_MA_12302' 'CL_MA_12303' 'CL_MA_12401' 'CL_MA_12402' 'CL_ML'
 'CL_ML_07101' 'CL_ML_07102' 'CL_ML_07103' 'CL_ML_07104' 'CL_ML_07105'
 'CL_ML_07106' 'CL_ML_07107' 'CL_ML_07108' 'CL_ML_07109' 'CL_ML_07110'
 'CL_ML_07201' 'CL_ML_07202' 'CL_ML_07203' 'CL_ML_07301' 'CL_ML_07302'
 'CL_ML_07303' 'CL_ML_07304' 'CL_ML_07305' 'CL_ML_07306' 'CL_ML_07307'
 'CL_ML_07308' 'CL_ML_07309' 'CL_ML_07401' 'CL_ML_07402' 'CL_ML_07403'
 'CL_ML_07404' 'CL_ML_07405' 'CL_ML_07406' 'CL_ML_07407' 'CL_ML_07408'
 'CL_NB' 'CL_NB_16101' 'CL_NB_16102' 'CL_NB_16103' 'CL_NB_16104'
 'CL_NB_16105' 'CL_NB_16106' 'CL_NB_16107' 'CL_NB_16108' 'CL_NB_16109'
 'CL_NB_16201' 'CL_NB_16202' 'CL_NB_16203' 'CL_NB_16204' 'CL_NB_16205'
 'CL_NB_16206' 'CL_NB_16207' 'CL_NB_16301' 'CL_NB_16302' 'CL_NB_16303'
 'CL_NB_16304' 'CL_NB_16305' 'CL_RM' 'CL_RM_13101' 'CL_RM_13102'
 'CL_RM_13103' 'CL_RM_13104' 'CL_RM_13105' 'CL_RM_13106' 'CL_RM_13107'
 'CL_RM_13108' 'CL_RM_13109' 'CL_RM_13110' 'CL_RM_13111' 'CL_RM_13112'
 'CL_RM_13113' 'CL_RM_13114' 'CL_RM_13115' 'CL_RM_13116' 'CL_RM_13117'
 'CL_RM_13118' 'CL_RM_13119' 'CL_RM_13120' 'CL_RM_13121' 'CL_RM_13122'
 'CL_RM_13123' 'CL_RM_13124' 'CL_RM_13125' 'CL_RM_13126' 'CL_RM_13127'
 'CL_RM_13128' 'CL_RM_13129' 'CL_RM_13130' 'CL_RM_13131' 'CL_RM_13132'
 'CL_RM_13201' 'CL_RM_13202' 'CL_RM_13203' 'CL_RM_13301' 'CL_RM_13302'
 'CL_RM_13303' 'CL_RM_13401' 'CL_RM_13402' 'CL_RM_13403' 'CL_RM_13404'
 'CL_RM_13501' 'CL_RM_13502' 'CL_RM_13503' 'CL_RM_13504' 'CL_RM_13505'
 'CL_RM_13601' 'CL_RM_13602' 'CL_RM_13603' 'CL_RM_13604' 'CL_RM_13605'
 'CL_TA' 'CL_TA_01101' 'CL_TA_01107' 'CL_TA_01401' 'CL_TA_01402'
 'CL_TA_01403' 'CL_TA_01404' 'CL_TA_01405' 'CL_VS' 'CL_VS_05101'
 'CL_VS_05102' 'CL_VS_05103' 'CL_VS_05104' 'CL_VS_05105' 'CL_VS_05107'
 'CL_VS_05109' 'CL_VS_05201' 'CL_VS_05301' 'CL_VS_05302' 'CL_VS_05303'
 'CL_VS_05304' 'CL_VS_05401' 'CL_VS_05402' 'CL_VS_05403' 'CL_VS_05404'
 'CL_VS_05405' 'CL_VS_05501' 'CL_VS_05502' 'CL_VS_05503' 'CL_VS_05504'
 'CL_VS_05506' 'CL_VS_05601' 'CL_VS_05602' 'CL_VS_05603' 'CL_VS_05604'
 'CL_VS_05605' 'CL_VS_05606' 'CL_VS_05701' 'CL_VS_05702' 'CL_VS_05703'
 'CL_VS_05704' 'CL_VS_05705' 'CL_VS_05706' 'CL_VS_05801' 'CL_VS_05802'
 'CL_VS_05803' 'CL_VS_05804']
Cantidad de códigos distintos (location_key) en Mexico: 2498

--- LISTA DE VALORES ÚNICOS MEX---
['MX' 'MX_AGU' 'MX_AGU_01001' ... 'MX_ZAC_32056' 'MX_ZAC_32057'
 'MX_ZAC_32058']
Cantidad de códigos distintos (location_key) en Peru: 1901

--- LISTA DE VALORES ÚNICOS PER---
['PE' 'PE_AMA' 'PE_AMA_0101' ... 'PE_UCA_0304' 'PE_UCA_0305' 'PE_UCA_0401']

Cantidad de códigos distintos (location_key) en Argentina: 5616

--- LISTA DE VALORES ÚNICOS ---
['BR' 'BR_AC' 'BR_AC_120001' ... 'BR_TO_172130' 'BR_TO_172208'
 'BR_TO_172210']

In [ ]:
# Lista de países donde se expandirá Biogenesys según location_key
paises_biogenesys = ["Argentina", "Brazil", "Chile", "Colombia", "Mexico", "Peru"]

# Mantener solo las filas donde 'country_name' esté en la lista
df_limpio = df_limpio[df_limpio["country_name"].isin(paises_biogenesys)]

print("Países filtrados: Ahora el data set df_limpio contiene solo:")
print(df_limpio["country_name"].unique())

# Mostrar el total de filas y columnas
print(f"Dimensiones del dataset: {df_limpio.shape}")